### ISSUE TITLE
multiple of 3 and 5

### ISSUE THREAD

**Issue by hemansnation** [HemansAI/algorithm-based-questions#1]
between 1 and 10, the numbers multiple of 3 or 5 are -- 3, 5, 6, 9, 10

now the sum of all the multiple are 3 + 5 + 6 + 9 + 10 = 33

get all the numbers between 1 to 1000 that are multiple of 3 or 5 and the print sum of them.

**Comment by Shashi-2** [comment]
[ISSUE.zip](https://github.com/HemansAI/algorithm-based-questions/files/8238184/ISSUE.zip)
